name: EMHASS (feature-variable_timestep)
version: "0.18.1-2a2d680"
slug: emhass-feature-variable_timestep
description: "EMHASS branch build: feature-variable_timestep"
url: "https://github.com/JoshC1994/emhass"
arch:
  - amd64
  - aarch64
homeassistant: "2023.1.0"
image: "ghcr.io/joshc1994/emhass"
init: false
map:
  - all:rw
options:
  no_entity_fetching: false
  publish_prefix: ""
  solcast_api_key: ""
  solcast_site_id: ""
  weather_entity: ""
  location_lat: ""
  location_lon: ""
  alt: 0
  module_power: 0
  module_count: 0
  inverter_power: 0
  Pd: 0
  eff: 100
  Pmax: 1000
  def_load: 0
schema:
  no_entity_fetching: bool
  publish_prefix: str
  solcast_api_key: str
  solcast_site_id: str
  weather_entity: str
  location_lat: str
  location_lon: str
  alt: int
  module_power: int
  module_count: int
  inverter_power: int
  Pd: int
  eff: int
  Pmax: int
  def_load: int
startup: services
boot: auto
ports:
  80/tcp: null
ports_description:
  80/tcp: EMHASS Web UI
environment:
  EMHASS_BRANCH: "feature-variable_timestep"
  EMHASS_COMMIT_SHA: "2a2d680f200254661ea805357c4c15e3ae3afe44"
